version: '3.4'

services:
  enrolled.api:

    container_name: enrolled.api

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=enroldb;Port=5432;Database=EnrolDb;User Id=admin;Password=admin1234;"
    depends_on:
      - enroldb
    ports:
      - "8002:80"

  enroldb:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=enrolDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=emre.kuru@ozu.edu.tr
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

